# Generated by Django 5.0.6 on 2025-09-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_location_conference_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='category',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='date',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='price',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='time',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='venue',
        ),
    ]
